sudo: required

language: c

services:
  - docker

before_install:
  - docker pull gapsystem/gap-docker

script:
  - docker version
  - docker run -t gapsystem/gap-docker sh -c 'cd /home/gap/inst/gap4r8/; sudo make testpackagesload; sudo wget https://raw.githubusercontent.com/gap-system/gap-docker-travis/master/postrun.sh ; sudo chmod u+x postrun.sh ; sudo ./postrun.sh' 

